### PR TITLE
Adding changelog

### PR DESCRIPTION
**Pull request by easypeasy944**
Adding change log by github_changelog_generator tool

### CODE REVIEW

**Comment by vladimirgoncharov** [comment]
Looks safely :) :+1: 

@nikitafomin Is it new practice? What for?

**Comment by nikitafomin** [comment]
@VladimirGoncharov it is request of Timur. And I think it is good idea.
I think we should stop for now and describe functional we wish see in first version.
Then describe all functional in change log.
For next versions we will create issues and discuss in which version we should implement new feature or fix bug.

**Comment by nikitafomin** [comment]
@VladimirGoncharov @NikolaevSergey @AynurGaliev @NikitaAsabin 
I think we should create changelog manually for first time. What do you think?

**Comment by vladimirgoncharov** [comment]
@nikitafomin I think we can discuss this in more detail on training

**Comment by kruperfone** [comment]
@nikitafomin 
What the difference between commit's history with Pivotal and changelog?
In its present form it will dump.

We use github+Pivotal intefration and mark all our PR, right?
So all what we need we can find in Pivotal.

**Comment by NikitaAsabin** [comment]
@nikitafomin  I think then if we create changelog manually it's will be better

**Comment by nikitafomin** [comment]
@NikolaevSergey I don't really sure what you said. We want add changelog only for base project. What for here Pivotal?

**Pull request closed without merging**
